# Generated by Django 4.1.7 on 2023-02-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
