# Generated by Django 4.1.7 on 2023-02-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_inquiry_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='is_active_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
